[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["npm ci --prefix aplikasi-server --omit=dev"]

[phases.build]
cmds = []

[start]
cmd = "cd aplikasi-server && node --no-warnings index.js"
