[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["npm ci --prefix aplikasi-server --production"]

[phases.build]
cmds = ["echo 'No build step needed for backend'"]

[start]
cmd = "cd aplikasi-server && npm start"
