[phases.setup]
nixPkgs = ["nodejs-20_x", "python311"]

[phases.install]
cmds = ["npm ci --production=false"]

[phases.build]
cmds = ["npm run install:server"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
NODE_OPTIONS = "--max-old-space-size=512"
