[build]
builder = "nixpacks"
buildCommand = "cd aplikasi-klien && npm ci && npm run build"

[deploy]
startCommand = "cd aplikasi-klien && npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
